podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - ${app}
    topologyKey: topology.kubernetes.io/zone