storage:
  ephemeral: true

replicas:
  master: 3
  tserver: 3
  totalMasters: 1

gflags:
  tserver:
    db_block_cache_size_percentage: 40
    global_memstore_size_mb_max: 1024
    memstore_arena_size_kb: 64

master:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "yb-master"
        topologyKey: kubernetes.io/hostname

tserver:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "yb-tserver"
        topologyKey: kubernetes.io/hostname
