
# Replace this with your own repo whitelist:
orgWhitelist: ${orgWhitelist}
github:
  user:   ${github_user}
  token:  ${github_token}
  secret: ${github_secret}
  # (The chart will perform the base64 encoding for you for values that are stored in secrets.)

## atlantis configuration

repoConfig: |
  ---
  repos:
  - id: /.*/
    apply_requirements: [approved, mergeable] 
    workflow: default
    allowed_overrides: [apply_requirements, workflow]
    allow_custom_workflows: true
  workflows:
    default:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]
