
version: 3
automerge: true
delete_source_branch_on_merge: true
parallel_plan: true
parallel_apply: true
projects:
  - name: k8s
    branch: /main/
    dir: https://github.com/glifio/filecoin-iac/k8s
    workspace: dev
    terraform_version: v1.3.1
    delete_source_branch_on_merge: true
    repo_locking: false
    autoplan:
      when_modified: ["*.tf", "../modules/**/*.tf"]
      enabled: true
    plan_requirements: [mergeable, approved, undiverged]
    apply_requirements: [mergeable, approved, undiverged]
    import_requirements: [mergeable, approved, undiverged]
    workflow: k8s
workflows:
  k8s:
    plan:
      steps:
        - init:
            extra_args: ["-backend-config=./filecoin-glif-dev-apn1.hcl"]
        - run: terraform init -backend-config=../filecoin-glif-dev-apn1.hcl
        - run: terraform workspace select filecoin-dev-apn1-glif-eks
        - plan:
            extra_args: ["-var-file=tfvars/filecoin-glif-dev-apn1.tfvars"]
        - run: terraform plan -var-file=tfvars/filecoin-glif-dev-apn1.tfvars
#    apply:
#      steps:
#        - run: echo hi
#        - apply
#allowed_regexp_prefixes:
#  - dev/
#  - staging/






















#
### atlantis.yaml file - This file overwrites the Server Side Repo Config section specfied in the values.yaml file
#version: 3
#automerge: true
#projects:
#  - name: k8s
#    dir: https://github.com/glifio/filecoin-iac/k8s
#    workspace: filecoin-dev-apn1-glif-eks
#    terraform_version: 1.3.1
#    autoplan:
#      enabled: true
#    workflow: k8s
#  - name: aws
#    dir: /https://github.com/glifio/filecoin-iac/aws
#    workspace: filecoin-glif-mainnet-apn1
#    terraform_version: 1.3.1
#    autoplan:
#      enabled: true
#    workflow: aws
#workflows:
#  k8s:
#    plan:
#      steps:
#        - init:
#            extra_args: [ "-backend-config=./filecoin-glif-dev-apn1.hcl" ]
#        - run: terraform workspace select $WORKSPACE
#        - plan:
#            extra_args: [ "-var-file", "-var-file=tfvars/filecoin-glif-dev-apn1.tfvars" ]