nodeSelector:
  nodepool: kong

ingressController:
  image:
    tag: 2.8
  installCRDs: false
  ingressClassAnnotations:
    ingressclass.kubernetes.io/is-default-class: true

proxy:
  tls:
    overrideServiceTargetPort: 8000
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  stream:
    - containerPort: 1235
      servicePort: 1235
      protocol: TCP
  annotations:
    prometheus.io/scrape: true
    prometheus.io/port: 10254


