project                     = "filecoin"
environment                 = "dev"
region                      = "ap-northeast-1"
sub_environment             = "glif"
route53_domain              = "dev.node.glif.io"
http_endpoint_uri = "https://node.glif.link/"
