prometheus:
  additionalServiceMonitors:
    - name: lotus-service
      selector:
        matchLabels:
          app: lotus-node-app
      namespaceSelector:
        matchNames:
          - network
      endpoints:
        - interval: 30s
          path: /debug/metrics
          port: tcp-api
          scheme: http
    - name: lotus-cache
      selector:
        matchLabels:
          app: lotus-cache
      namespaceSelector:
        matchNames:
          - network
      endpoints:
        - interval: 30s
          path: /metrics
          port: cache-port
          scheme: http
  additionalPodMonitors:
    - name: kong
      namespaceSelector:
        matchNames:
          - kong
      selector:
        matchLabels:
          app.kubernetes.io/name: kong
      podMetricsEndpoints:
        - interval: 30s
          targetPort: 8100
          scheme: http
          path: /metrics
