commonLabels:
  environment: ${get_short_environment}

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      nodeGroupName: ${get_nodegroup_selector}

  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: "${get_slack_api_url}"
    templates: ["*.tmpl"]
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 15m
      repeat_interval: 12h
      receiver: "slack-notification"
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
        - match:
            alertname: InfoInhibitor
          receiver: 'null'
    receivers:
      - name: "slack-notification"
        slack_configs:
          - channel: '${get_slack_channel}'
            send_resolved: true
            title: '{{ template "custom_title" . }}'
            text: '{{ template "custom_slack_message" . }}'
      - name: "null"

  ## Alertmanager template files to format alerts
  ## ref: https://prometheus.io/docs/alerting/notifications/
  ##      https://prometheus.io/docs/alerting/notification_examples/
  ##
  templateFiles:
    notificationsSlack.tmpl: |
      {{ define "slack.default.username" }}Alert-dev{{ end }}
      {{ define "__single_message_title" }}{{ range .Alerts.Firing }}{{ .Labels.alertname }} @ {{ .Annotations.summary }}{{ end }}{{ range .Alerts.Resolved }}{{ .Labels.alertname }} @ {{ .Annotations.summary }}{{ end }}{{ end }}
      {{ define "custom_title" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if or (and (eq (len .Alerts.Firing) 1) (eq (len .Alerts.Resolved) 0)) (and (eq (len .Alerts.Firing) 0) (eq (len .Alerts.Resolved) 1)) }}{{ template "__single_message_title" . }}{{ end }}{{ end }}
      {{ define "custom_slack_message" }}
                {{ range .Alerts -}}
                *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
                *Description:* {{ .Annotations.description }}
                *Details:*
                  {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                  {{ end }}
                {{ end }}
      {{ end }}

## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  nodeSelector:
    nodeGroupName: ${get_nodegroup_selector}
  grafana.ini:
    unified_alerting:
      enabled: false
    server:
      root_url: "https://${get_grafana_notif_url}/"
  notifiers:
    notifiers.yaml:
      notifiers:
        - name: "notification-channel-1"
          type: "slack"
          uid: "slacknotifier"
          org_id: 1
          is_default: true
          send_reminder: true
          frequency: "1h"
          disable_resolve_message: false
          # TODO: should be changed to secure_settings after upgrade to grafana more than 7.1.5
          settings:
            url: "${get_grafana_notifiers_url}"
  ## custom dashboards
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'custom'
          orgId: 1
          folder: 'lotus'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/custom
  dashboards:
    custom:
      LotusAPIEndpoints:
        datasource: Prometheus
        gnetId: 13251
        revision: 8
      LotusNodeHealth:
        datasource: Prometheus
        gnetId: 13250
        revision: 6
      LotusPubSubdashboard:
        datasource: Prometheus
        gnetId: 13249
        revision: 2
      LotusNginx:
        datasource: Prometheus
        gnetId: 13901
        revision: 2
      LotusVolumes:
        datasource: Prometheus
        gnetId: 17092
        revision: 7
      Kong:
        datasource: Prometheus
        gnetId: 7424
        revision: 9

## Component scraping the kubelet and kubelet-hosted cAdvisor
kubelet:
  serviceMonitor:
    resource: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

prometheusOperator:
  nodeSelector:
    nodeGroupName: ${get_nodegroup_selector}
  admissionWebhooks:
    patch:
      nodeSelector:
        nodeGroupName: ${get_nodegroup_selector}

  createCustomResource: true
  cleanupCustomResource: false

prometheus:
  prometheusSpec:
    nodeSelector:
      nodeGroupName: ${get_nodegroup_selector}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 120d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ${get_prometheus_storage_class}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: ${get_pvc_size}

  additionalServiceMonitors:
    - name: lily-service
      selector:
        matchLabels:
          app.kubernetes.io/instance: calib10
          app.kubernetes.io/name: filecoin
      namespaceSelector:
        matchNames:
          - ${get_app_namespace}
      endpoints:
        - interval: 30s
          path: /metrics
          port: metrics
          scheme: http
    - name: lotus-service
      selector:
        matchLabels:
          app: lotus-node-app
      namespaceSelector:
        matchNames:
          - ${get_app_namespace}
      endpoints:
        - interval: 30s
          path: /debug/metrics
          port: tcp-api
          scheme: http
    - name: kong-external-ingress
      selector:
        matchLabels:
          app.kubernetes.io/instance: ${get_kong_ingress_external}
      namespaceSelector:
        matchNames:
          - kong
      endpoints:
        - interval: 30s
          port: metrics
          scheme: http
          path: /metrics
    - name: kong-internal-ingress
      selector:
        matchLabels:
          app.kubernetes.io/instance: ${get_kong_ingress_internal}
      namespaceSelector:
        matchNames:
          - kong
      endpoints:
        - interval: 30s
          port: metrics
          scheme: http
          path: /metrics
    - name: lotus-cache
      selector:
        matchLabels:
          app: lotus-cache
      namespaceSelector:
        matchNames:
          - ${get_app_namespace}
      endpoints:
        - interval: 30s
          path: /metrics
          port: cache-port
          scheme: http
