prometheus:
  additionalPodMonitors:
    - name: default-kong
      namespaceSelector:
        matchNames:
          - kong
      selector:
        matchLabels:
          app: default-kong
      podMetricsEndpoints:
        - interval: 30s
          targetPort: 8100
          scheme: http
          path: /metrics
    - name: spacenet
      namespaceSelector:
        matchNames:
          - network
      selector:
        matchLabels:
          release: spacenet
      podMetricsEndpoints:
        - interval: 30s
          targetPort: 8100
          scheme: http
          path: /metrics
