prometheus:
  additionalServiceMonitors:
    - name: lotus-service
      selector:
        matchLabels:
          app: lotus-node-app
      namespaceSelector:
        matchNames:
          - network
      endpoints:
        - interval: 30s
          path: /debug/metrics
          port: tcp-api
          scheme: http
  additionalPodMonitors:
    - name: default-kong
      namespaceSelector:
        matchNames:
          - kong
      selector:
        matchLabels:
          app: default-kong
      podMetricsEndpoints:
        - interval: 30s
          targetPort: 8100
          scheme: http
          path: /metrics
